### ISSUE TITLE
VLC Not Opening on macOS

### ISSUE THREAD

**Issue by neo-neo1** [tarkah/lazystream#101]
Command `lazystream --date 20220111 play select` 

Fails with error:
```
[cli][info] Found matching plugin hls for URL [REDACTED_URL.m3u8]
[cli][info] Available streams: 670k (worst), 1000k, 1400k, 2100k, 2900k, 4100k, 6600k (best)
[cli][info] Opening stream: 6600k (hls)
[cli][info] Starting player: vlc
error: Failed to start player: vlc ([Errno 2] No such file or directory: 'vlc')
[cli][info] Closing currently open stream...
```

To verify this works and VLC opens:
```
streamlink REDACTED_URL_m3u8 --http-no-ssl-verify
``` 
Note: By default VLC install on macOS is not in path env in terminal. To open VLC from terminal: `/Applications/VLC.app/Contents/MacOS/VLC`

**Comment by tarkah** [comment]
Weird streamlink works by itself but not in lazystream w/ VLC not in env path

If you add it to your path, it should 100% work.
