### ISSUE TITLE
No Games?

### ISSUE THREAD

**Issue by neauxm** [tarkah/lazystream#104]
I haven't been able to use this in a couple weeks. "Stream not available yet, will check again soon"

Is this still being updated?

**Comment by tlsnine** [comment]
Same!

The freegamez url isn't responding to pings anymore, and while the freesports ddns url does respond to ping, it isn't allowing any streaming.

Tried both CDN's as well.

Seems like a few of the other apps like this aren't working either.

Has the encryption changed or is the backend server just down?

Thanks!
