### ISSUE TITLE
MLB not working

### ISSUE THREAD

**Issue by SnooPac** [tarkah/lazystream#107]
I cannot get MLB to work. It always just says `Stream not available yet, will check again soon...` when trying to record.

Also tried to generate playlist, NHL seems to create proper m3u8 list. But MLB looks like:
`#EXTM3U`
`#EXTINF:-1 CUID="1000" tvg-id="1000" tvg-name="Lazyman 1",1:05 PM Red Sox @ Yankees HOME`
`.`
`#EXTINF:-1 CUID="1001" tvg-id="1001" tvg-name="Lazyman 2",1:05 PM Red Sox @ Yankees AWAY`
`.`
`#EXTINF:-1 CUID="1002" tvg-id="1002" tvg-name="Lazyman 3",1:10 PM White Sox @ Tigers HOME`
(no actual links)

NHL is working with LazyStream. And TooLazy (kodi addon) seems to be working now with MLB.
So in theory this should be able to work.

Not sure if it's something on my end?

**Comment by tarkah** [comment]
Try passing `--quality 720p60` on the command line and see if it works. I think this is currently needed for some reason. 

You can try other qualities as well if you don't want that one.

**Comment by SnooPac** [comment]
Thanks for the suggestion.
Unfortunately though, getting the same problem as before.

**Comment by SnooPac** [comment]
So, yesterday's weren't (and still aren't) working.
But today's seem to be working (without needing --quality btw). So hopefully yesterday was just a one-off. Closing this issue.

Thanks
