### ISSUE TITLE
When selecting MLB game, ERROR: missing field `preview` at line 4 column 19

### ISSUE THREAD

**Issue by yamyamyamyamyam** [tarkah/lazystream#112]
Hi, just trying to compile and use/update this project, ran into an issue where after selecting an MLB game, the program would just spit out ``ERROR: missing field `preview` at line 4 column 19``. I compiled the program and tried to debug it, but I'm on macOS with relatively little Rust experience and couldn't even figure out where this error was being spit out, and it seems like you can't really set breakpoints on Rust error creation with lldb. If you're still around hope you see this and can provide some guidance!

**Comment by tarkah** [comment]
Looking into this now

**Comment by tarkah** [comment]
Fixed in https://github.com/tarkah/lazystream/releases/tag/v1.12.1
