### ISSUE TITLE
Record - Filename

### ISSUE THREAD

**Issue by schwyl** [tarkah/lazystream#12]
When using the record function have it label the file with the date and team names from the stream

YYYY-MM-DD - Teams

**Comment by tarkah** [comment]
Hmm, this is the format that it should be saving in...

https://github.com/tarkah/lazystream/blob/2bbe8e41acb55e7c68ddf4ded647bcf7d69d725c/src/streamlink.rs#L313-L322

What filename format is being saved for you?

**Comment by schwyl** [comment]
schwyl@DockerHost01:~/lazystream$ ./lazystream --date 20200201 record team EDM /home/schwyl/fileserver/data_testing/
Found matching team for EDM
Game found for today
Using stream feed NATIONAL

Recording with StreamLink...

============================

[cli][info] Found matching plugin hls for URL hlsvariant://https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1580734201~acl=/*~id=nhlGatewayId:9849948~data=71013503~hmac=bd8d265a9560ed08c6fc83f806cd8ff53a3eda6d47c46216e9cd73f35c203281/a33a56b076d4560f89cf84f875e73fb7/ls03/nhl/2020/02/02/NHL_GAME_VIDEO_EDMCGY_M2_NATIONAL_20200202_1579378477196/master_wired60.m3u8
[cli][info] Available streams: 216p (worst), 288p, 360p, 504p, 540p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)


Gives a filename of 244X2I~K.MP4

**Comment by tarkah** [comment]
Huh... That's so weird.. does it do that for other games as well?

**Comment by schwyl** [comment]
Yep just tried a Chicago game from the same day and its a gibberish filename

**Comment by tarkah** [comment]
Here is my output:

```
tarkah on solus-home in ~
❯ lazystream record team EDM --date 20200201 /tmp
Found matching team for EDM
Game found for today
Using stream feed NATIONAL

Recording with StreamLink...

============================

[cli][info] Found matching plugin hls for URL hlsvariant://https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1580734201~acl=/*~id=nhlGatewayId:9849948~data=71013503~hmac=bd8d265a9560ed08c6fc83f806cd8ff53a3eda6d47c46216e9cd73f35c203281/a33a56b076d4560f89cf84f875e73fb7/ls03/nhl/2020/02/02/NHL_GAME_VIDEO_EDMCGY_M2_NATIONAL_20200202_1579378477196/master_wired60.m3u8
[cli][info] Available streams: 216p (worst), 288p, 360p, 504p, 540p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[download][..ary Flames NATIONAL.mp4] Written 125.5 MB (3s @ 33.9 MB/s)                                          ^C[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...


tarkah on solus-home in ~ took 7s
❯ ll /tmp/2020-02-01\ 7\:00\ PM\ Edmonton\ Oilers\ @\ Calgary\ Flames\ NATIONAL.mp4
-rw-rw-r-- 1 tarkah tarkah 136167272 Feb  2 20:45 '/tmp/2020-02-01 7:00 PM Edmonton Oilers @ Calgary Flames NATIONAL.mp4'
```

**Comment by tarkah** [comment]
What version of Streamlink are you using? I'm using 1.3.0

**Comment by schwyl** [comment]
1.8.0

**Comment by tarkah** [comment]
The dependency Streamlink, not my program. I'm passing the filename to that, I'd suspect it's a bug with Streamlink.

**Comment by schwyl** [comment]
Oh ok ill go that route

**Comment by tarkah** [comment]
Try installing Streamlink 1.3.0 if you don't already have that version, to see if we can rule out that as the issue. I'm going to also dig through their Issues and see if anything matches this issue.

**Comment by schwyl** [comment]
Im sorry Im running 1.31 of streamlink 1.8 of your program

**Comment by tarkah** [comment]
@schwyl are you still having this problem? Have you been able to try on a different computer / different version of Streamlink?

**Comment by schwyl** [comment]
Hey,

I dunno what happened but it just started working a few days after I
posted. Go ahead and close this

**Comment by tarkah** [comment]
Great!
