### ISSUE TITLE
Creating XML's from two instanaces

### ISSUE THREAD

**Issue by schwyl** [tarkah/lazystream#21]
Im using this to generate files for Live TV.

Ive set up both one cronjob for NHL and one for MLB

The issue is in the XML file its tagging the channel identifier the same in both xml files.
[lazystreamer_xml_m3u.zip](https://github.com/tarkah/lazystream/files/4253092/lazystreamer_xml_m3u.zip)

This is causing issues with the guide populating the wrong channel information. The streams are correct but the guide is wrong.

These are the two commands that were ran to generate the attached files

./lazystream --quality 720p generate xmltv /home/user/nhl.m3u --start-channel 9000
./lazystream --sport mlb --quality 720p generate xmltv /user/mlb.m3u --start-channel 10000

**Comment by tarkah** [comment]
Are you referring to the channel name being the following for both, even though they have different channel numbers?


```
Lazyman 1
Lazyman 2
Lazyman 3
```

**Comment by schwyl** [comment]
Yes.

**Comment by tarkah** [comment]
Got it. So this would be a breaking change for other users and their xmltv setup if I change the name to add "MLB" and "NHL" to it.

How about I add an option that allows you to specify a custom channel name, like `--channel-prefix` so you could do `--channel-prefix "Lazyman MLB"`?

**Comment by schwyl** [comment]
yep that would suffice

**Comment by tarkah** [comment]
Cool, I'll add this tomorrow.

**Comment by schwyl** [comment]
It also has to do the m3u as well

**Comment by tarkah** [comment]
@schwyl checkout latest release, it has this option `--channel-prefix`
