### ISSUE TITLE
ensure all 100 channels exist on xmltv output

### ISSUE THREAD

**Issue by tarkah** [tarkah/lazystream#28]
xmltv output should always have all 100 channels filled in on the m3u and xml files. Otherwise this causes issues w/ dynamic channel count and programs like xTeVe / Plex DVR

**Comment by gokraken** [comment]
@tarkah would you be willing to add a env flag for not adding the blank channels?   Depending on how active you are I can try and then issue a PR but I haven't coded in rust and if you're active you'll be much faster.   Thanks!

**Comment by tarkah** [comment]
This would be super easy to add! I can do this quickly tomorrow 👍

**Comment by gokraken** [comment]
Awesome, thank you!  I'm assuming you'll write it this way, but the default should be including the blank channels.  I wouldn't want my change to break everyone else!

**Comment by tarkah** [comment]
@gokraken sorry for the delay, I haven't forgotten this request, I'll try to get it done within the next couple days!

**Comment by tarkah** [comment]
@gokraken So sorry for the delay. I just released https://github.com/tarkah/lazystream/releases/tag/v1.11.8. There is a `--trim` flag I added for `xmltv` that will trim out the blank channels, so it'll only publish as many channels as there are streams.
