### ISSUE TITLE
Use hostname instead of IP when casting

### ISSUE THREAD

**Issue by schwyl** [tarkah/lazystream#33]
Would be great to be able to use host name as well as IP when casting

**Comment by tarkah** [comment]
Let me enable passing a String on the command line instead of checking for a valid IPv4 address. This will get passed to VLC's  --sout-chromecast-ip option, so if that ends up accepting a hostname, it should work!

**Comment by tarkah** [comment]
@schwyl You can try this out by building from source on the linked PR #35. I won't be able to test this until probably tomorrow, so I'll wait to merge until either you confirm it works, or I am able to test myself.

**Comment by schwyl** [comment]
Ok I'll try it after the games are over lol

**Comment by tarkah** [comment]
@schwyl I still haven't had a chance to try this out at home yet, have you confirmed if it works?

**Comment by schwyl** [comment]
no sorry got called back to work. ill have to try in in 2 weeks lol

**Comment by tarkah** [comment]
ok, I'll try to test in next couple days then and merge if all is good

**Comment by tarkah** [comment]
Just confirmed this works! :+1:
