### ISSUE TITLE
Error passing to player

### ISSUE THREAD

**Issue by Datagrdn** [tarkah/lazystream#43]
Hey there, really psyched to use this but having some issues getting up and running. I'm try to load in mpv per above but getting the following error. Any suggestions?

Passing game to player...

============================

[cli][info] Found matching plugin hls for URL hlsvariant://https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596519653~acl=/*~id=nhlGatewayId:3238580~data=2000009351~hmac=368e1b7480d8757d441bdf81efbc268f72aaa20f907b70146eded342041a6970/11426becaba7ffb12506e9070a093e8c/ls03/nhl/2020/08/02/NHL_GAME_VIDEO_PHIBOS_M2_NATIONAL_20200802_1595879014740/master_wired60.m3u8 name_key=bitrate
[cli][info] Available streams: 670k (worst), 1000k, 1450k, 2140k, 2900k, 4100k, 6600k (best)
[cli][info] Opening stream: 6600k (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000009351/kid/70324982 (400 Client Error: Bad Request for url: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000009351/kid/70324982)
[cli][error] Try 1/3: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596519653~acl=/*~id=nhlGatewayId:3238580~data=2000009351~hmac=368e1b7480d8757d441bdf81efbc268f72aaa20f907b70146eded342041a6970/11426becaba7ffb12506e9070a093e8c/ls03/nhl/2020/08/02/NHL_GAME_VIDEO_PHIBOS_M2_NATIONAL_20200802_1595879014740/5600K/5600_complete-trimmed.m3u8')> (No data returned from stream)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000009351/kid/70324982 (400 Client Error: Bad Request for url: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000009351/kid/70324982)
[cli][error] Try 2/3: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596519653~acl=/*~id=nhlGatewayId:3238580~data=2000009351~hmac=368e1b7480d8757d441bdf81efbc268f72aaa20f907b70146eded342041a6970/11426becaba7ffb12506e9070a093e8c/ls03/nhl/2020/08/02/NHL_GAME_VIDEO_PHIBOS_M2_NATIONAL_20200802_1595879014740/5600K/5600_complete-trimmed.m3u8')> (No data returned from stream)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000009351/kid/70324982 (400 Client Error: Bad Request for url: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000009351/kid/70324982)
[cli][error] Try 3/3: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596519653~acl=/*~id=nhlGatewayId:3238580~data=2000009351~hmac=368e1b7480d8757d441bdf81efbc268f72aaa20f907b70146eded342041a6970/11426becaba7ffb12506e9070a093e8c/ls03/nhl/2020/08/02/NHL_GAME_VIDEO_PHIBOS_M2_NATIONAL_20200802_1595879014740/5600K/5600_complete-trimmed.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596519653~acl=/*~id=nhlGatewayId:3238580~data=2000009351~hmac=368e1b7480d8757d441bdf81efbc268f72aaa20f907b70146eded342041a6970/11426becaba7ffb12506e9070a093e8c/ls03/nhl/2020/08/02/NHL_GAME_VIDEO_PHIBOS_M2_NATIONAL_20200802_1595879014740/5600K/5600_complete-trimmed.m3u8')>, tried 3 times, exiting
[cli][info] Closing currently open stream...

**Comment by AndrewATruong** [comment]
[Add these entries](https://github.com/acleee/lm-ips/blob/master/lm_hosts.txt) to your `hosts` file. It grabs the stream decryptor from a different source that will allow you to watch the streams.

**Comment by tarkah** [comment]
@AndrewATruong thanks for linking that resource.

I'll update the README with these instructions as more people might find this that don't have experience with LazyMan.

**Comment by Datagrdn** [comment]
Thanks for this. Indeed I setup LazyMan so long ago on another machine and don't remember that process so forgive me if this is redundant. That helped but now I'm getting the following Streamlink error. Worth noting that I tried running streamlink CLI for this link directly, it worked the first time but was super choppy, but now when I run the same link I get "Could not open stream" error.

Thanks again, details from Lazystream below:


Passing game to player...

============================

[cli][info] Found matching plugin hls for URL hlsvariant://https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596570004~acl=/*~id=nhlGatewayId:3532287~data=2000008511~hmac=39e6e93fb01c0a297de86e3ede638546c390d753a0d082f5710c12ba8e050e6a/4a55d94987f008553d1ba8475d85b376/ls03/nhl/2020/08/03/NHL_GAME_VIDEO_WPGCGY_M2_NATIONAL_20200803_1595823935794/master_wired60.m3u8 name_key=bitrate
[cli][info] Available streams: 670k (worst), 1000k, 1450k, 2140k, 2900k, 4100k, 6600k (best)
[cli][info] Opening stream: 6600k (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000008511/kid/70324311 (400 Client Error: Bad Request for url: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000008511/kid/70324311)
[cli][error] Try 1/3: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596570004~acl=/*~id=nhlGatewayId:3532287~data=2000008511~hmac=39e6e93fb01c0a297de86e3ede638546c390d753a0d082f5710c12ba8e050e6a/4a55d94987f008553d1ba8475d85b376/ls03/nhl/2020/08/03/NHL_GAME_VIDEO_WPGCGY_M2_NATIONAL_20200803_1595823935794/5600K/5600_complete.m3u8')> (No data returned from stream)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000008511/kid/70324311 (400 Client Error: Bad Request for url: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000008511/kid/70324311)
[cli][error] Try 2/3: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596570004~acl=/*~id=nhlGatewayId:3532287~data=2000008511~hmac=39e6e93fb01c0a297de86e3ede638546c390d753a0d082f5710c12ba8e050e6a/4a55d94987f008553d1ba8475d85b376/ls03/nhl/2020/08/03/NHL_GAME_VIDEO_WPGCGY_M2_NATIONAL_20200803_1595823935794/5600K/5600_complete.m3u8')> (No data returned from stream)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000008511/kid/70324311 (400 Client Error: Bad Request for url: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2000008511/kid/70324311)
[cli][error] Try 3/3: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596570004~acl=/*~id=nhlGatewayId:3532287~data=2000008511~hmac=39e6e93fb01c0a297de86e3ede638546c390d753a0d082f5710c12ba8e050e6a/4a55d94987f008553d1ba8475d85b376/ls03/nhl/2020/08/03/NHL_GAME_VIDEO_WPGCGY_M2_NATIONAL_20200803_1595823935794/5600K/5600_complete.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1596570004~acl=/*~id=nhlGatewayId:3532287~data=2000008511~hmac=39e6e93fb01c0a297de86e3ede638546c390d753a0d082f5710c12ba8e050e6a/4a55d94987f008553d1ba8475d85b376/ls03/nhl/2020/08/03/NHL_GAME_VIDEO_WPGCGY_M2_NATIONAL_20200803_1595823935794/5600K/5600_complete.m3u8')>, tried 3 times, exiting
[cli][info] Closing currently open stream...

ERROR: StreamLink failed
(base) jon@Jons-MacBook-Air lazystream-master %

**Comment by tarkah** [comment]
Hmm, still seems like a dns issue... Did you try restarting after making the hosts file update?

**Comment by tarkah** [comment]
When in doubt, try pinging mf.svc.nhl.com and you should get the IP from the hosts file update

**Comment by Datagrdn** [comment]
Ah, see what I did wrong now. We're up and running, thanks so much!

**Comment by tarkah** [comment]
Great! Enjoy some playoffs :)
