### ISSUE TITLE
lazystream license type

### ISSUE THREAD

**Issue by conrad-fox** [tarkah/lazystream#46]
I was wondering what open source license lazystream falls under? I was looking into setting up a homebrew formula for the software to make it even easier to download/install on macOS

**Comment by eblanchette** [comment]
Less people who knows about the app less chance it gets shut down.

**Comment by tarkah** [comment]
I can always throw an MIT license at it. However, on top of what @eblanchette said, this isn't really a program that "just works" due to DNS updates. I provide binaries for all platforms on each release, so users inclined to get this working should just come to this repo.

**Comment by conrad-fox** [comment]
Good point. I'm going to close this issue due to those reasons alone.
