### ISSUE TITLE
--quality 720p60 option plays adaptive stream

### ISSUE THREAD

**Issue by AndrewATruong** [tarkah/lazystream#48]
Hi there! It seems like that `--quality 720p60` flag plays the highest bitrate available from the adaptive stream when passing to streamlink, but because it's still adaptive, it leads to some issues when I cast the stream (whether I use this app's cast function, or use the play function and cast from the VLC GUI) If possible, it'd be great if setting the quality flag would use the dedicated m3u8 for the 720p60 quality.

Context: When casting the adaptive stream to my Chromecast device (at least for me), if the quality changes VLC disconnects from the cast device for 15-30 seconds before switching to a lower bitrate which I find pretty annoying. In my experience on other devices if I force the player to use the highest quality bitrate, it'll play without buffering problems even if using the adaptive setting would downgrade to a lower quality.

Here's a modified version of what I see:
```
lazystream cast select --quality 720p60

{I select the game and feed and cast device}

Casting with StreamLink...

============================

[cli][info] Found matching plugin hls for URL [...]/master_wired60.m3u8 name_key=bitrate
[cli][info] Available streams: 670k (worst), 1000k, 1450k, 2140k, 2900k, 4100k, 6600k (best)
[cli][info] Opening stream: 6600k (hls)
[cli][info] Starting player: vlc -I dummy --sout "#chromecast" --sout-chromecast-ip=X.X.X.X --demux-filter=demux_chromecast
```

Thanks!

**Comment by tarkah** [comment]
Oh yeah, this shouldn't be a problem! I already have a function for returning the dedicated m3u8 link for each quality, which works when you use the `select` or `generate` subcommands. For cast, play and record, since it uses streamlink under the hood, I passed the quality setting on to it. But I can just pass the actual dedicated link instead, good call!

**Comment by tarkah** [comment]
This has been merged and included in the newest release:

https://github.com/tarkah/lazystream/releases/tag/v1.10.5
