### ISSUE TITLE
Do the links work in Android?

### ISSUE THREAD

**Issue by airbete** [tarkah/lazystream#5]
The links work great in desktop VLC, but they don't work in VLC for Android. Is it normal? I always get this message: "The location [...] cannot be played."

Thanks

**Comment by tarkah** [comment]
Yeah I'm not sure, I've never gotten any of these links to work on my Android with any media player. Not exactly sure why. Though that functionality is outside the scope of this program, I'll leave this issue open to see if anyone else can weigh in on if / how the streams can work natively on Android.

Have you checked /r/LazyMan for any answers?

**Comment by airbete** [comment]
I am not familiar with LazyMan, but I have found old posts describing the exact problem I have, e.g. https://www.reddit.com/r/LazyMan/comments/b9lcaz/are_there_any_android_apps_capable_of/ek6xtqp?utm_source=share&utm_medium=web2x

I didn't manage to find a solution though.

Anyway thank you for Lazystream, still very useful on desktop. ;-)

**Comment by tarkah** [comment]
No problem, it's been fun building this! Hopefully you find a good solution. I'm getting the games to stream to my phone via xTeVe / Plex with great quality. Might be worth looking into if you already use Plex.
