### ISSUE TITLE
[Feature Request] Add file output option

### ISSUE THREAD

**Issue by conrad-fox** [tarkah/lazystream#50]
Would it be possible for you to add an option to the `lazystream select` command to save output to a file? Would be much appreciated :)

**Comment by tarkah** [comment]
You can use `lazystream generate playlist` and I think that gives you what you want

**Comment by conrad-fox** [comment]
Ah okay, I think I can work with that

**Comment by tarkah** [comment]
What are you needing specific output for?

**Comment by conrad-fox** [comment]
My original thought was just to have the resolved link (for the game I'm interested in) in a file that I could read in from another script. Normally I would just use pipes or redirects but since `lazystream select --resolve` expect user input the pipe (at least my experience with pipe) doesn't allow me to see stdout from lazystream to make the selections

**Comment by tarkah** [comment]
Ahh I see. Let me know if you are able to parse the playlist output.
