### ISSUE TITLE
Compile / Install instructions?

### ISSUE THREAD

**Issue by barberws** [tarkah/lazystream#53]
Not a developer here, but am comfortable on linux command line. I can install any necessary dependencies. Can someone provide a checklist for compiling and installing?

Thanks!

**Comment by tarkah** [comment]
No external dependencies needed :) Just make sure to have rust / cargo installed and...

```
cargo build --release
```

that will create the binary in `target/release/lazystream`

**Comment by barberws** [comment]
Thanks!  Might want to add that to the Readme. I found your project on reddit, so I'm betting you're going to be getting more non-dev traffic soon.  I appreciate your work!

**Comment by tarkah** [comment]
I actually post binaries for each platform via releases:

https://github.com/tarkah/lazystream/releases/latest

These should all work out of the box since no dependencies are dynamically linked. I'll add that link to the README as I just noticed it's missing.

**Comment by barberws** [comment]
Awesome. Thanks!
