### ISSUE TITLE
Failed to start player: vlc

### ISSUE THREAD

**Issue by cbunyked** [tarkah/lazystream#61]
Is there an updated host file?

**Comment by tarkah** [comment]
See here:

https://github.com/tarkah/lazystream/issues/54#issuecomment-765494174

**Comment by cbunyked** [comment]
Thanks. I saw that and it doesn't seem to be working for me. I'm getting ERROR: Streamlink failed.

```Passing game to player...

============================

[cli][info] Found matching plugin hls for URL hlsvariant://https://hlslive-l3c.med2.med.nhl.com/token=exp=1611447680~id=nhlGatewayId:1239075~data=2013261291~hash=93517660aae3b2f20dec78fb86d63060cbf1184b/ls03/nhl/2021/01/23/NHL_GAME_VIDEO_EDMTOR_M2_HOME_20210123_1610390339433/master_wired60.m3u8 name_key=bitrate
[cli][info] Available streams: 670k (worst), 1000k, 1450k, 2140k, 2900k, 4100k, 6600k (best)
[cli][info] Opening stream: 6600k (hls)
[cli][info] Starting player: vlc
error: Failed to start player: vlc ([Errno 2] No such file or directory: 'vlc')
[cli][info] Closing currently open stream...

ERROR: StreamLink failed

**Comment by cbunyked** [comment]
Oh, wait. I see the error could be my VLC player

**Comment by tarkah** [comment]
My comment on the other thread:

@cbunyked Based on the error, it doesn't appear you have VLC in your PATH. Are you on windows or linux? On windows, it should be something like `C:\Program Files\VideoLAN\VLC` for vlc and `C:\Users\{{your user}}\AppData\Local\Streamlink\bin` for streamlink (also needed installed and in path).

And if you're on linux, doubt I have to point you in the right direction there ;)

**Comment by cbunyked** [comment]
Hmm. No luck. Still getting the same error. Basically, I created a symlink of vlc and streamlink on /usr/local/bin which is declared on my zshrc. I'm on MacOS Big Sur.

**Comment by cbunyked** [comment]
Ended up installing VLC via Homebrew. For some reason installing the app from the site and linking it on my path didn't like it. I'm good to go now. Thanks for this : )
