### ISSUE TITLE
MLB issues(?)

### ISSUE THREAD

**Issue by nexxai** [tarkah/lazystream#66]
Just wondering if this is expected:

```sh
➜ ./lazystream select --sport mlb

 |        \   __  /\ \   / ___|__ __|  _ \  ____|    \     \  |
 |       _ \     /  \   /\___ \   |   |   | __|     _ \   |\/ |
 |      ___ \   /      |       |  |   __ <  |      ___ \  |   |
_____|_/    _\____|   _| _____/  _|  _| \_\_____|_/    _\_|  _|


ERROR: missing field `abbreviation` at line 1 column 673
```

**Comment by Evilmnkey** [comment]
Lazyman just got the MLB fix in yesterday, Guessing will be fixed soon here

**Comment by nexxai** [comment]
Wasn't lazyman abandoned?

**Comment by Evilmnkey** [comment]
He returned 2 days ago, re opened the reddit and GitHub pages

**Comment by nexxai** [comment]
Ahh cool

**Comment by tarkah** [comment]
Nice! I didn't realize this. Let me get a fix for this out ASAP then.

**Comment by tarkah** [comment]
@nexxai Ok this is fixed, however it doesn't appear that any MLB links are actually posted yet. I've confirmed in the LazyMan application that they can't be streamed there yet either. Once those links are posted (assuming they get posted in the same way as before), it should _just work_ here as well.

I'll publish a new release shortly.

**Comment by nexxai** [comment]
Awesome thanks man!
