### ISSUE TITLE
720p60 Streams issue

### ISSUE THREAD

**Issue by Evilmnkey** [tarkah/lazystream#69]
Hi, each time i run this "lazystream.exe --sport mlb --quality 720p60 generate xmltv mlb" it seems to only give me the SD stream
same if i use 720p quality

Can you look into it please? when i check the Lazyman app itself it outputs the 720 fine

thanks

**Comment by tarkah** [comment]
Yeah let me dig into it

**Comment by tarkah** [comment]
Ahh, I know why. It's how I parse the master.m3u8 file. Before the only line to have a FRAME-RATE key on it was the 720p60 line. But now ALL qualities have a FRAME-RATE key which is throwing off my logic. 

This should be an easy fix.

**Comment by Evilmnkey** [comment]
not the same as the NHL export?
Awesome, always with the quick fixes

**Comment by tarkah** [comment]
NHL m3u8 only includes the FRAME-RATE key for the 720p60 quality line. At least for now, maybe this will also change. Either way, my fix will cover that in the future if it does change.

No problem! Pushing out the fix here in a few minutes.
