### ISSUE TITLE
n00b here looking for help!

### ISSUE THREAD

**Issue by bunkfunk44** [tarkah/lazystream#72]
I downloaded the ios version (apple-darwin) and in the zip are just the lazystream (terminal) and the readme.  When I open the terminal, it acts as if it loads the instructions, but says "Process completed" at the bottom and I can't type any further commands (solid block). 
If I open a fresh terminal window and type "$ lazystream --help" it says "-bash: lazystream: command not found"

What am I doing wrong here? Thanks for the help!

**Comment by tarkah** [comment]
ios as in iphone? It's not compiled for that target, just macos. That'd explain the command not found error you're getting.

**Comment by bunkfunk44** [comment]
er sorry! mac os! I have a mid-2010 mac pro on High Sierra (10.13.6)

**Comment by bunkfunk44** [comment]
this is what the terminal looks like when I open lazystream.  I can't type after this. It is just sort of locked here.
![Screen Shot 2021-04-09 at 7 57 47 PM](https://user-images.githubusercontent.com/82247832/114256423-0b4d4e00-996e-11eb-8eb1-d9055eed22b3.png)

**Comment by tarkah** [comment]
It's a terminal program, so you need to run it from a terminal. Double clicking the binary will result in what you're seeing.

Make sure you're in the directory the program is in and run it with `./lazystream`

**Comment by bunkfunk44** [comment]
OK I think I got it! Thanks for your help.  Still having trouble getting streamlink to pull the links up in vlc (says "Failed to create decryptor: Unable to open URL" after the two [cli] [info] lines.  But that may be out of your realm of expertise since you didn't write streamlink!  I'd appreciate any further help on that but no worries if not since you got me this far!!!

**Comment by tarkah** [comment]
No problem! Make sure your hosts file is updated otherwise it won't work. You can see this comment:

https://github.com/tarkah/lazystream/issues/54#issuecomment-765494174
