### ISSUE TITLE
Error running Lazystream

### ISSUE THREAD

**Issue by Evilmnkey** [tarkah/lazystream#73]
THis just started today

lazystream.exe --sport nhl select

 |        \   __  /\ \   / ___|__ __|  _ \  ____|    \     \  |
 |       _ \     /  \   /\___ \   |   |   | __|     _ \   |\/ |
 |      ___ \   /      |       |  |   __ <  |      ___ \  |   |
_____|_/    _\____|   _| _____/  _|  _| \_\_____|_/    _\_|  _|

←[31mERROR←[0m: missing field `shortName` at line 1197 column 3

anyway you can have a look, MLB seems to be listing

**Comment by mlindgren80** [comment]
Same issue here on macOS and Linux with v1.11.4

**Comment by ThatNickPrice** [comment]
Also having the same issue here, started yesterday

`missing field 'shortName' at line 1197 column 3` when running against NHL games. 

Additionally, I'm seeing `missing field 'abbreviation' at line 1 column 673` when running against MLB games

**Comment by coffee-beard** [comment]
BEWARE THE KRAKEN!

Released less than a fortnight ago, ye Kraken already be laying they foe to waste. This evil is so strong no league may call it by any [other name](https://statsapi.web.nhl.com/api/v1/teams). Slay they beast by never seeking to call it by a short name. Not once, but strike (https://github.com/tarkah/lazystream/blob/master/src/api/model.rs#L15) and the loose tentacles of death  (https://github.com/tarkah/stats-api/blob/master/src/model/nhl.rs#L21). Then sleep well... until next the Kraken attacks they lazy rust vessel.

**Comment by mlindgren80** [comment]
> BEWARE THE KRAKEN!
> 
> Released less than a fortnight ago, ye Kraken already be laying they foe to waste. This evil is so strong no league may call it by any [other name](https://statsapi.web.nhl.com/api/v1/teams). Slay they beast by never seeking to call it by a short name. Not once, but strike (https://github.com/tarkah/lazystream/blob/master/src/api/model.rs#L15) and the loose tentacles of death (https://github.com/tarkah/stats-api/blob/master/src/model/nhl.rs#L21). Then sleep well... until next the Kraken attacks they lazy rust vessel.

I don't know what this means :D Should I comment out those lines?

**Comment by sumofatguy** [comment]
same issue with me, windows 10 pro

`missing field 'shortName' at line 1197 column 3`

**Comment by fedorajoe** [comment]
Same here.  Fedora 33.

**Comment by chesh1r3k** [comment]
> BEWARE THE KRAKEN!
> 
> Released less than a fortnight ago, ye Kraken already be laying they foe to waste. This evil is so strong no league may call it by any [other name](https://statsapi.web.nhl.com/api/v1/teams). Slay they beast by never seeking to call it by a short name. Not once, but strike (https://github.com/tarkah/lazystream/blob/master/src/api/model.rs#L15) and the loose tentacles of death (https://github.com/tarkah/stats-api/blob/master/src/model/nhl.rs#L21). Then sleep well... until next the Kraken attacks they lazy rust vessel.

I get that the Kraken was added to the NHL API, but what needs to be done to fix the code?

**Comment by ThatNickPrice** [comment]
I don't think the code is broken... NHL's API is. As @coffee-beard hilariously pointed out:

> This evil is so strong no league may call it by any [other name](https://statsapi.web.nhl.com/api/v1/teams)

the Kraken were added to the NHL's stats API, but weren't given a shortName attribute, which every other team has and Lazystream tries to load. 

> Slay they beast by never seeking to call it by a short name. Not once, but strike (https://github.com/tarkah/lazystream/blob/master/src/api/model.rs#L15) and the loose tentacles of death (https://github.com/tarkah/stats-api/blob/master/src/model/nhl.rs#L21)

Aside from the two instances linked above, It doesn't look like the `shortName` field is getting used anywhere else. You might be able to just comment out that part of the model.

**Comment by tarkah** [comment]
Sorry all, I've been out camping this weekend. I'll try to get a quick patch for this released tonight when I get home.

**Comment by tarkah** [comment]
New release is out with a fix for this!

**Comment by sumofatguy** [comment]
Thank you!

> 
> 
> New release is out with a fix for this!
