### ISSUE TITLE
MLB M3U/XMLTV Generation Throws Error

### ISSUE THREAD

**Issue by SoSJames** [tarkah/lazystream#74]
Running the latest version, the option to generate M3U/XMLTV for MLB now fails with error:

ERROR: missing field `name` at line 1 column 42001

NHL works as expected, and MLB worked fine up until 5/27/2021.

I'm guessing something changed with the MLB API and how it returns the schedule.

**Comment by tarkah** [comment]
I'll push out a fix for this shortly.

**Comment by tarkah** [comment]
Fixed in https://github.com/tarkah/lazystream/releases/tag/v1.11.6

**Comment by SoSJames** [comment]
Thanks again!
