### ISSUE TITLE
Unable to create XML file for NHL

### ISSUE THREAD

**Issue by italy333333** [tarkah/lazystream#78]
When trying to create an XML file for NHL I receive the following error, MLB is fine though.

/ # lazystream generate xmltv /playlists/lazystream/lazystream-nhl --sport mlb --date 20210926
Creating .m3u & .xml for XMLTV...
Playlist saved to: "/playlists/lazystream/lazystream-nhl.m3u"
Xmltv file saved to: "/playlists/lazystream/lazystream-nhl.xml"
/ # lazystream generate xmltv /playlists/lazystream/lazystream-nhl --sport nhl --date 20210926
Creating .m3u & .xml for XMLTV...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/stream.rs:305:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/ #

**Comment by sumofatguy** [comment]
I am getting the same issue. Windows 10 server. MLB works fine, NHL output is below:

```
lazystream.exe generate xmltv C:\webapps\lazystream-xteve\nhl --quality 720p60 --cdn l3c
Creating .m3u & .xml for XMLTV...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\stream.rs:324:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tarkah** [comment]
Thanks for the reports! Something always seems to break with the API each season. I'll look into this.

**Comment by tarkah** [comment]
One of the API responses is malformed. Instead of panicking, it'll just skip the game(s) with API issues and generate a file for the other games.

**Comment by nexxai** [comment]
When the PR is built, will you be tagging a new point release?

**Comment by tarkah** [comment]
Yup! Just doing some more testing, but will release shortly.
