### ISSUE TITLE
NHL M3U Creation Fails, MLB Working

### ISSUE THREAD

**Issue by SoSJames** [tarkah/lazystream#80]
Now that NHL preseason has begun, I'm seeing that the script fails to retrieve NHL games (which are available from Lazyman/NHLGames). Trying to create an M3U causes this error:

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/stream.rs:324:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tarkah** [comment]
Just pushed a fix for this in the latest release https://github.com/tarkah/lazystream/releases/tag/v1.11.7

**Comment by SoSJames** [comment]
As usual, you're the best! Thanks!
