### ISSUE TITLE
Issue w/URL Generated 

### ISSUE THREAD

**Issue by seanz251** [tarkah/lazystream#81]
Running this on a Linux cloud machine, I've noticed when trying to generate any links I don't get the **nhl**.(restofthedomainprefix) as seen in the Lazystream Wiki. 

For example, I'll just get; 
http://freegamez.ga/getM3U8.php?league=nhl&date=2021-10-13&id=2026706631&cdn=akc 

I can't get streams to work and wonder if this is an issue with setup?

**Comment by timbenroeck** [comment]
If you are only running the select command it will return this url.  If you curl this URL you will get the link you are expecting.

**Comment by tarkah** [comment]
There is a flag you can pass on command line `--resolve` that'll resolve this URL for you
