### ISSUE TITLE
Stream not available error

### ISSUE THREAD

**Issue by un999** [tarkah/lazystream#83]
Getting Stream not available error for all live streams and for yesterdays concluded streams.  Possibly the issue, LM shut down today and freegamez dot ga is offline.  Other app is suggesting to switch to freesports dot ddns dot net

Thank you for your kind attention

**Comment by MaDTaZ** [comment]
Update to the newest version the url is fixed in that V1.11.8
https://github.com/tarkah/lazystream/releases/tag/v1.11.8
