### ISSUE TITLE
Lazyman dev quit

### ISSUE THREAD

**Issue by Evilmnkey** [tarkah/lazystream#84]
Unsure if this is related but freegamez.ga offline, please switch to freesports.ddns.net in Settings
This is from the nhl_games app

Dont see option to switch in the commands

**Comment by MaDTaZ** [comment]
Look at the setting that is the same Ip that freegamez.ga was using as well.   Looks like Lazyman main guy has quit after another site got raided 

If I use the command line and get url it still work fine so at least I can still do that.  
freesports.ddns.net is the one to use now the other one has now completely gone down

Update main.rs #85

**Comment by tarkah** [comment]
Fix released in https://github.com/tarkah/lazystream/releases/tag/v1.11.8

Thanks @MaDTaZ !

**Comment by MaDTaZ** [comment]
if I use @taylorbourne / xteve_lazystream. do I just have to restart and it will grab the update of this?

**Comment by tarkah** [comment]
Yup! It checks for updates when containers boots up.

I've also pushed an updated to the Dockerfile so it can be rebuilt from that on Master. Dockerhub hasn't been updated yet.

**Comment by MaDTaZ** [comment]
K I think that is my issue I have your installed standalone and then I have his for my main one to update Emby.  So I think I am just waiting for dockerhub to update.
