### ISSUE TITLE
Lazyman is no more. Will you be able to update it to use  NHL games

### ISSUE THREAD

**Issue by schwyl** [tarkah/lazystream#87]
Lazyman is no more. Will you be able to update it to use  NHL games

**Comment by tarkah** [comment]
Checkout v1.11.8 which I just released that fixes this :)

**Comment by MaDTaZ** [comment]
It worked great by the way!!! HEHE

**Comment by schwyl** [comment]
Lol Nice.

How do I update it in the docker?

**Comment by chesh1r3k** [comment]
I just tested v1.11.8 w/ the Islanders game that's on right now and can't get it to tune.  This is what I'm seeing in my logs:

`2021/10/30 12:04:10 [xTeVe] Buffer: true [ffmpeg]
2021/10/30 12:04:10 [xTeVe] Buffer Size: 5120 KB
2021/10/30 12:04:10 [xTeVe] Channel Name: Lazystream: NHL 1
2021/10/30 12:04:10 [xTeVe] Client User-Agent: Lavf/58.27.104
2021/10/30 12:04:11 [xTeVe] Streaming Status: Playlist: nhl - Tuner: 1 / 4
2021/10/30 12:04:11 [xTeVe] FFMPEG path: /usr/bin/ffmpeg
2021/10/30 12:04:11 [xTeVe] Streaming URL: <redacted>
2021/10/30 12:04:11 [xTeVe] FFMPEG: Processing data
2021/10/30 12:04:11 [xTeVe] Streaming Status: Receive data from FFMPEG
2021/10/30 12:04:13 [xTeVe] FFMPEG log: [hls @ 0x14948a395640] Unable to open key file <redacted>
2021/10/30 12:04:14 [xTeVe] FFMPEG log: [hls @ 0x14948a395640] Error when loading first segment <redacted>

2021/10/30 12:04:14 [xTeVe] FFMPEG log: <redacted>: Invalid data found when processing input
2021/10/30 12:04:14 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204

2021/10/30 12:04:14 [xTeVe] Streaming Status: Client has terminated the connection
2021/10/30 12:04:14 [xTeVe] Streaming Status: Channel: Lazystream: NHL 1 (Clients: 0)
2021/10/30 12:04:15 [xTeVe] Streaming Status: Channel: Lazystream: NHL 1 - No client is using this channel anymore. Streaming Server connection has ended
2021/10/30 12:04:15 [xTeVe] Streaming Status: Playlist: nhl - Tuner: 0 / 4`

**Comment by tarkah** [comment]
If you have the latest docker image, you should just be able to restart your container and it'll grab the latest version of this program.

**Comment by tarkah** [comment]
Crap, I need to update the host in the docker image as well. You can use lazystream directly for now until a fix for that is pushed out.

**Comment by schwyl** [comment]
Lol Thanks Boss but im getting this error when the docker image goes to pull the new version

[update-lazystream] checking for update,
[update-lazystream] installed version: v1.11.6,
[update-lazystream] remote version: v1.11.8,
[update-lazystream] newer version available, downloading...,
Connecting to github.com (140.82.113.4:443),
wget: server returned error: HTTP/1.1 404 Not Found,
tar: can't open 'lazystream.tar.gz': No such file or directory,
mv: cannot stat '././lazystream': No such file or directory,
rm: cannot remove 'lazystream.tar.gz': No such file or directory,
[update-lazystream] lazystream successfully updated to v1.11.8,
[cont-init.d] 60-update-lazystream: exited 0.,
[cont-init.d] 70-chown-files: executing... ,
[cont-init.d] 70-chown-files: exited 0.,
[cont-init.d] 99-firstrun: executing... ,

**Comment by tarkah** [comment]
Ok, new docker image has been pushed with all the needed fixes!! Please pull the new `latest` tag and you should be good to go.

**Comment by schwyl** [comment]
Yep All good now lol

Thanks

**Comment by chesh1r3k** [comment]
All good here, as well. Thanks!
