### ISSUE TITLE
The new --trim feature 

### ISSUE THREAD

**Issue by MaDTaZ** [tarkah/lazystream#88]
So I am trying to get it to work and using this as the arguement is that correct
 nhl_args+=("--trim")
I think reading it over I need to specifically call out the m3u

something like this
nhl_args+=("--trim" "lazystream-nhl.m3u")

**Comment by tarkah** [comment]
Open this up on the xteve repo. --trim should be able to be positioned anywhere after the `xmltv` subcommand

**Comment by MaDTaZ** [comment]
I got it to work look like this now

nhl_args=()                                            
                nhl_args+=("--trim")                                   
                nhl_args+=("--exclude-feeds" "COMPOSITE" "FRENCH")     
                nhl_args+=("--channel-prefix")                         
                nhl_args+=("Lazystream: NHL")                          
                nhl_args+=("--start-channel")                          
                nhl_args+=("1000")                                  
                nhl_args+=("/playlists/lazystream/lazystream-nhl")
