### ISSUE TITLE
Add option to translate url

### ISSUE THREAD

**Issue by conrad-fox** [tarkah/lazystream#9]
Currently the url that is returned from lazystream needs to be resolved to receive the hls link. I would nice to have the option to return this value. Assumes users host file is setup correctly (whether local or resolved upstream (ex: Pihole))

**Comment by tarkah** [comment]
Good call. I already have all the functions to do this as I am feeding the actual hls link into the playlist and xmltv output options. 

I'm reworking the command line interface a bit since this program is growing in scope. I'll add this once I push that out.

**Comment by tarkah** [comment]
I'll be merging this shortly, the option will be available in the newest release.

I've changed the cli so what used to be `lazyman` is now `lazyman select`.  You can use `lazyman select --resolve` to resolve the host link to the master m3u8 link.
