### ISSUE TITLE
Latest Version no longer Populating M3U with links?

### ISSUE THREAD

**Issue by Riles554** [tarkah/lazystream#90]
Yesterday seemed to be working fine - Noticed that no option is pulling NHL M3U links at this time. Is the new host broken?

**Comment by Riles554** [comment]
Just double checked - If I manually pull games it appears to be working - Just getting blank output if I pull full playlists for NHL or MLB

**Comment by tarkah** [comment]
Are you sure the links are posted?

I am not seeing any links using `lazystream select --resolve`, which would explain why the m3u is blank. Yesterday's date populates fine.

**Comment by Riles554** [comment]
You're right. When I pulled with `select` it was generating links, but not working ones. Looking at /r/NHL_games it appears there is an issue with the host server again. Too bad.

**Comment by taylorbourne** [comment]
@Riles554 stay tuned for #86

**Comment by tarkah** [comment]
Update your hosts file with current IP from `ping freesports.ddns.net`

**Comment by Riles554** [comment]
@taylorbourne @tarkah it appears the updated hosts fix works for now! Thank you very much. I truly appreciate the attentiveness to these projects and the fact that you're monitoring each other's so diligently.

**Comment by Evilmnkey** [comment]
Still failing for me it seems, Host file updated and all

**Comment by MaDTaZ** [comment]
> Still failing for me it seems, Host file updated and all

Be sure to use the --resolve tag if was the only way I could get it to work.  

./lazystream select --sport nhl --resolve
I also can use this command that I always use now as well ./lazystream play team CHI  so look like the NHL God are shining on us tonight

**Comment by Evilmnkey** [comment]
Yea still hating me. thanks for our info. Ill mess with it tomorrow

**Comment by tarkah** [comment]
@Evilmnkey @Riles554 Is this still an issue or can I close this?

**Comment by Evilmnkey** [comment]
Haven't had time to get to it, but yea go ahead and close it. thanks
