### ISSUE TITLE
Error “zsh command not found: lazystream”

### ISSUE THREAD

**Issue by loyahdev** [tarkah/lazystream#91]
I don’t understand why this happens and it’ll happen every time

**Comment by tarkah** [comment]
Is the binary not in your path?

**Comment by Galorlx** [comment]
What do you mean?

**Comment by Galorlx** [comment]
> Is the binary not in your path?

What do you mean?

**Comment by loyahdev** [comment]
![image](https://user-images.githubusercontent.com/68242406/140099450-3d846d4c-2d94-4c3f-93db-20c22101616b.jpg)
Like it just says process completed when I in the file

**Comment by tarkah** [comment]
How are you running the command?

Run it from your terminal.

**Comment by Galorlx** [comment]
Still no

Uploading 65764963765__9E5BFB4B-7DF3-4148-B56E-5A59CD1D950B.MOV…

**Comment by loyahdev** [comment]
![image](https://user-images.githubusercontent.com/68242406/140101836-f2972890-2e07-44ab-8ddb-7e63f37dfa6e.jpg)

still no

**Comment by loyahdev** [comment]
> How are you running the command?
> 
> Run it from your terminal.

Nope
