### ISSUE TITLE
“ERROR: Could not find and run StreamLink. Please ensure it is installed and accessible from your PATH”

### ISSUE THREAD

**Issue by loyahdev** [tarkah/lazystream#93]
I have stream link installed but wherever I put the install it’ll never work.
![image](https://user-images.githubusercontent.com/68242406/140187063-48e6dec5-d986-421a-89a4-66080c7f618d.jpg)
![image](https://user-images.githubusercontent.com/68242406/140187135-0d3be25f-c6b0-4ea1-a1a4-52bea81ed2ad.jpg)

**Comment by tarkah** [comment]
`export PATH=$PATH:/path/to/streamlink`

**Comment by loyahdev** [comment]
Still have same error 
![image](https://user-images.githubusercontent.com/68242406/140193713-cdfc4826-912d-41ee-9772-62a6fbffa256.jpg)

**Comment by loyahdev** [comment]
> export PATH=$PATH:/path/to/streamlink

Yeah that didn’t work

**Comment by loyahdev** [comment]
It also won’t let me play any games from the link just this
![EC28FA52-DDC1-49F9-AF99-3D46C7245A40](https://user-images.githubusercontent.com/68242406/140236719-236a3c5e-ad8d-4e39-9edb-d3a025dedc59.jpeg)
